<a href="https://colab.research.google.com/github/deboradcm/IARTES/blob/master/06_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Máquina de Vetores de Suporte

In [1]:
import numpy as np
import pandas as pd

### Carregando os dados

https://archive.ics.uci.edu/ml/datasets/breast+cancer

In [2]:
from sklearn import datasets

In [3]:
breast = datasets.load_breast_cancer()

In [4]:
type(breast)

sklearn.utils._bunch.Bunch

In [5]:
print(breast.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [6]:
breast.data.shape

(569, 30)

In [7]:
breast.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
breast.target_names[breast.target]

array(['malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'malignant', 'malignant', 'malignant', 'benign',
       'benign', 'benign', 'malignant', 'malignant', 'malignant',
       'malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'malignant', 'benign', 'malignant', 'malignant',
       'malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'benign', 'malignant', 'benign', 'benign', 'benign',
       'benign', 'benign', 'malignant', 'malignant', 'benign',
       'malignant', 'malignant', 'benign', 'benign', 'benign', 'benign',
       'malignant', 'benign', 'malignant', 'malignant', 'benign',
       'benign', 'benign', 'benign', 'malignant', 'benign', 'malignant',
       'malignan

In [9]:
import sklearn.svm

In [10]:
dir (sklearn.svm)

['LinearSVC',
 'LinearSVR',
 'NuSVC',
 'NuSVR',
 'OneClassSVM',
 'SVC',
 'SVR',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_bounds',
 '_classes',
 '_liblinear',
 '_libsvm',
 '_libsvm_sparse',
 'l1_min_c']

In [11]:
from sklearn.svm import SVC

In [12]:
svc = SVC(kernel='linear', C=0.01)

In [13]:
dir(breast)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
svc.fit(breast.data, breast.target)

SVC(C=0.01, kernel='linear')

In [15]:
svc.coef_

array([[ 3.34170043e-02,  1.01818969e-02, -6.80079804e-02,
         1.48857342e-02, -5.20883605e-03, -9.59361733e-03,
        -1.69409000e-02, -7.94293455e-03, -7.22566582e-03,
        -1.34490336e-03, -1.52444946e-03,  1.91139193e-02,
         1.51041127e-02, -1.96938973e-02, -7.12765120e-04,
        -1.01539748e-03, -2.88342647e-03, -1.00945138e-03,
        -8.62254074e-04, -9.12643364e-05,  7.55609920e-03,
        -1.39541997e-01, -1.26934669e-01, -5.77838975e-03,
        -1.00728819e-02, -3.22245652e-02, -4.78452228e-02,
        -1.60069277e-02, -1.73056022e-02, -4.60459536e-03]])

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
ypred = svc.predict(breast.data)

In [18]:
ypred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [19]:
acuracia = accuracy_score(breast.target, ypred)
acuracia

0.9525483304042179

In [20]:
1 - accuracy_score(breast.target, ypred) #erro empirico (serve para ver se ele ta com alto viés)

0.047451669595782064

### Seleção e Validação

### Treino e Teste

Use `train_test_split` para dividir a amostra em dois subconjutos. Um conjuto de treino e um conjunto de teste.

Use isso para calcular o erro de *hold-out*.

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
len(train_test_split(breast.data))

2

In [23]:
len(train_test_split(breast.data, breast.target))

4

In [24]:
Xtrain, Xtest, ytrain, ytest = train_test_split(breast.data, breast.target, test_size = 4, stratify=breast.target)

In [25]:
Xtest.shape

(4, 30)

In [26]:
pd.Series(breast.target).value_counts()/ len(breast.target)

1    0.627417
0    0.372583
dtype: float64

In [27]:
pd.Series(breast.target).value_counts() / len(ytest)

1    89.25
0    53.00
dtype: float64

In [28]:
pd.Series(breast.target).value_counts() / len(ytest)

1    89.25
0    53.00
dtype: float64

In [29]:
pd.Series(breast.target).value_counts() / len(ytest)

1    89.25
0    53.00
dtype: float64

In [30]:
svc = SVC(kernel='linear', C=0.001)

In [31]:
svc.fit(Xtrain, ytrain)

SVC(C=0.001, kernel='linear')

In [32]:
accuracy_score(ytrain, svc.predict(Xtrain))

0.9504424778761061

In [45]:
accuracy_score(ytrain, svc.predict(Xtest))

ValueError: Found input variables with inconsistent numbers of samples: [565, 4]

### Treino, Teste e Validação

In [35]:
Xtest.shape

(4, 30)

## Ajuste de hiperparâmetros

In [37]:
C = [0.1, 1, 10, 100, 1000]
gamma = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5]

In [38]:
resultados = {}

In [42]:
for c in C:
    print(f"Treinando com C={c}")

    for g in gamma:
        svm = SVC(kernel='rbf', C=c, gamma=g);

        svm.fit(X_train, y_train)
        ypred = svm.predict(X_val)

        acc = accuracy_score(y_val, ypred)

        resultados[(c, g)] = acc

Treinando com C=0.1


NameError: name 'X_train' is not defined

In [46]:
resultados

{}

In [44]:
melhor_acc = 0
melhor_chave = None

for chave in resultados:
    if resultados[chave] > melhor_acc:
        melhor_chave = chave
        melhor_acc = resultados[chave]

In [47]:
melhor_chave

In [48]:
melhor_acc

0

In [49]:
svm_test = SVC(kernel='rbf', C=1, gamma=0.001)

In [50]:
svm_test.fit(X_aux, y_aux)

NameError: name 'X_aux' is not defined

In [51]:
ypred = svm_test.predict(X_test)

NameError: name 'X_test' is not defined

In [52]:
accuracy_score(y_test, ypred)

NameError: name 'y_test' is not defined

In [53]:
svm_final = SVC(kernel='rbf', C=1, gamma=0.001)

In [54]:
svm_final.fit(breast.data, breast.target)

SVC(C=1, gamma=0.001)

In [55]:
svm.support_vectors_.shape

AttributeError: 'SVC' object has no attribute 'support_vectors_'